branch-defaults:
  default:
    environment: FunNetflixSearcher-dev
    group_suffix: null
global:
  application_name: FunNetflixSearcher
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
